AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: pll_handler.my_handler
      Runtime: python3.6
      CodeUri: .

  hello:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.hello
      Runtime: python3.6
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /hello
            Method: any

  solveForComponents:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.solveComponents
      Runtime: python3.6
      Events:
        ListCustomers:
          Type: Api
          Properties:
            Path: /solveForComponents
            Method: any